apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: cnn-feature-server
spec:
  selector:
    matchLabels:
      app: cnn-feature-server
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: cnn-feature-server
        tier: frontend
    spec:
      containers:
      - name: python-rest-server
        image: jayantduneja1234/rest-server-gke:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: REDIS_HOST
          value: redis
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: UTF-8
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: minio
        - name: MINIO_PORT
          value: "9000"
        - name : POSTGRES_HOST
          value : postgres
        - name : POSTGRES_PORT
          value : "5432"
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 5000
---